vlog -work work E:/Documents-bkp/UFRN/TCC/Quartus/riscv_microcontroller/simulation/modelsim/microcontroller.vwf.vt
vsim -novopt -c -t 1ps -L cycloneiv_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.microcontroller_vlg_vec_tst
onerror {resume}
add wave {microcontroller_vlg_vec_tst/i1/debug_controller_state}
add wave {microcontroller_vlg_vec_tst/i1/debug_controller_state[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_controller_state[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_controller_state[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_pc_output[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x31_output[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x1_output[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_x2_output[0]}
add wave {microcontroller_vlg_vec_tst/i1/clock}
add wave {microcontroller_vlg_vec_tst/i1/reset}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_regfile_write}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_0[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_input_1[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_1}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_1[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_1[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_1[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_1[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_1[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_immediate[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_mux0_sel}
add wave {microcontroller_vlg_vec_tst/i1/debug_mux0_sel[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_mux0_sel[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_operation}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_operation[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_operation[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_operation[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_operation[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_forward_mux_0}
add wave {microcontroller_vlg_vec_tst/i1/debug_forward_mux_0[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_forward_mux_0[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_forward_mux_1}
add wave {microcontroller_vlg_vec_tst/i1/debug_forward_mux_1[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_forward_mux_1[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_EX_MEM}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_EX_MEM[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_EX_MEM[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_EX_MEM[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_EX_MEM[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_EX_MEM[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0_ID_EXE}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0_ID_EXE[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0_ID_EXE[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0_ID_EXE[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0_ID_EXE[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_read_address_0_ID_EXE[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_read_address_0_from_IF}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_read_address_0_from_IF[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_read_address_0_from_IF[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_read_address_0_from_IF[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_read_address_0_from_IF[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_read_address_0_from_IF[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_mux0_sel_from_MEM}
add wave {microcontroller_vlg_vec_tst/i1/debug_mux0_sel_from_MEM[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_mux0_sel_from_MEM[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_from_MEM}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_from_MEM[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_from_MEM[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_from_MEM[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_from_MEM[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_address_from_MEM[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_reg_file_write_from_MEM}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_MEM[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_ALU_output_from_EX[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_0_from_ID[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_register_file_output_1_from_ID[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_PC_operation}
add wave {microcontroller_vlg_vec_tst/i1/debug_PC_operation[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_PC_operation[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_PC_operation[0]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[31]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[30]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[29]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[28]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[27]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[26]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[25]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[24]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[23]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[22]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[21]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[20]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[19]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[18]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[17]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[16]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[15]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[14]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[13]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[12]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[11]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[10]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[9]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[8]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[7]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[6]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[5]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[4]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[3]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[2]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[1]}
add wave {microcontroller_vlg_vec_tst/i1/debug_instruction[0]}
run -all
